In [7]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

In [8]:
a = pd.read_csv("bank.csv")
print(a)

      Variance  Skewness  Curtosis  Entropy  Class
0      3.62160   8.66610   -2.8073 -0.44699      0
1      4.54590   8.16740   -2.4586 -1.46210      0
2      3.86600  -2.63830    1.9242  0.10645      0
3      3.45660   9.52280   -4.0112 -3.59440      0
4      0.32924  -4.45520    4.5718 -0.98880      0
...        ...       ...       ...      ...    ...
1367   0.40614   1.34920   -1.4501 -0.55949      1
1368  -1.38870  -4.87730    6.4774  0.34179      1
1369  -3.75030 -13.45860   17.5932 -2.77710      1
1370  -3.56370  -8.38270   12.3930 -1.28230      1
1371  -2.54190  -0.65804    2.6842  1.19520      1

[1372 rows x 5 columns]


In [9]:
print(a.shape)
print(a.describe())

(1372, 5)
          Variance     Skewness     Curtosis      Entropy        Class
count  1372.000000  1372.000000  1372.000000  1372.000000  1372.000000
mean      0.433735     1.922353     1.397627    -1.191657     0.444606
std       2.842763     5.869047     4.310030     2.101013     0.497103
min      -7.042100   -13.773100    -5.286100    -8.548200     0.000000
25%      -1.773000    -1.708200    -1.574975    -2.413450     0.000000
50%       0.496180     2.319650     0.616630    -0.586650     0.000000
75%       2.821475     6.814625     3.179250     0.394810     1.000000
max       6.824800    12.951600    17.927400     2.449500     1.000000


In [10]:
c = a.corr
print(c)    

<bound method DataFrame.corr of       Variance  Skewness  Curtosis  Entropy  Class
0      3.62160   8.66610   -2.8073 -0.44699      0
1      4.54590   8.16740   -2.4586 -1.46210      0
2      3.86600  -2.63830    1.9242  0.10645      0
3      3.45660   9.52280   -4.0112 -3.59440      0
4      0.32924  -4.45520    4.5718 -0.98880      0
...        ...       ...       ...      ...    ...
1367   0.40614   1.34920   -1.4501 -0.55949      1
1368  -1.38870  -4.87730    6.4774  0.34179      1
1369  -3.75030 -13.45860   17.5932 -2.77710      1
1370  -3.56370  -8.38270   12.3930 -1.28230      1
1371  -2.54190  -0.65804    2.6842  1.19520      1

[1372 rows x 5 columns]>


In [11]:
print(a.head())

   Variance  Skewness  Curtosis  Entropy  Class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0


In [12]:
x = a.drop("Class", axis = 1)
print(x)

      Variance  Skewness  Curtosis  Entropy
0      3.62160   8.66610   -2.8073 -0.44699
1      4.54590   8.16740   -2.4586 -1.46210
2      3.86600  -2.63830    1.9242  0.10645
3      3.45660   9.52280   -4.0112 -3.59440
4      0.32924  -4.45520    4.5718 -0.98880
...        ...       ...       ...      ...
1367   0.40614   1.34920   -1.4501 -0.55949
1368  -1.38870  -4.87730    6.4774  0.34179
1369  -3.75030 -13.45860   17.5932 -2.77710
1370  -3.56370  -8.38270   12.3930 -1.28230
1371  -2.54190  -0.65804    2.6842  1.19520

[1372 rows x 4 columns]


In [13]:
y = a['Class']
print(y)

0       0
1       0
2       0
3       0
4       0
       ..
1367    1
1368    1
1369    1
1370    1
1371    1
Name: Class, Length: 1372, dtype: int64


In [16]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2) 

In [18]:
print(len(x))

1372


In [19]:
print(len(X_test))

275


In [20]:
print(X_train)

      Variance  Skewness  Curtosis   Entropy
700    3.92620   6.02990  -2.01560 -0.065531
221    2.41960   6.46650  -0.75688  0.228000
1026   0.11806   0.39108  -0.98223  0.428430
82     5.01850   8.59780  -2.93750 -1.281000
1186  -4.24400 -13.06340  17.11160 -2.801700
...        ...       ...       ...       ...
1288  -2.65900  -1.60580   1.36470  0.164640
718    4.09320   5.41320  -1.82190  0.235760
465   -2.69890  12.19840   0.67661 -8.548200
158    2.26340  -4.48620   3.65580 -0.612510
1008  -1.94090  -8.68480   9.15500  0.940490

[1097 rows x 4 columns]


In [21]:
print(X_test)

      Variance  Skewness  Curtosis  Entropy
115    2.53310   2.91350  -0.82200 -0.12243
169    0.11739   6.27610  -1.54950 -2.47460
463   -1.94580  11.22170   1.90790 -3.44050
1312   0.55939  -0.31040   0.18307  0.44653
1234  -4.94620   3.57160   0.82742 -1.49570
...        ...       ...       ...      ...
346    4.09720   0.46972   1.66710  0.91593
829   -2.24820   3.09150  -2.39690 -2.67110
199    5.88620   5.87470  -2.81670 -0.30087
1028  -2.72640   3.92130  -0.49212 -3.63710
13    -1.57680  10.84300   2.54620 -2.93620

[275 rows x 4 columns]


In [22]:
scaler = StandardScaler()
h = scaler.fit(X_train)
print(h)

StandardScaler()


In [23]:
X_train = scaler.transform(X_train)
print(X_train)

[[ 1.23190799  0.7117183  -0.80263638  0.53427154]
 [ 0.70023057  0.78627575 -0.51059645  0.67337771]
 [-0.11198026 -0.25121357 -0.56288067  0.76836274]
 ...
 [-1.10608222  1.76510273 -0.17800753 -3.48571818]
 [ 0.64510777 -1.08409852  0.51320454  0.27505478]
 [-0.83858489 -1.80108643  1.78909275  1.01103116]]


In [24]:
X_test = scaler.transform(X_test)
print(X_test)

[[ 0.74028459  0.17953588 -0.52570516  0.50730675]
 [-0.1122167   0.75376146 -0.69449492 -0.60740128]
 [-0.84031409  1.59831331  0.10766828 -1.06514731]
 ...
 [ 1.92358974  0.68521505 -0.98850233  0.42274292]
 [-1.11578694  0.3516362  -0.44916857 -1.15831727]
 [-0.71009441  1.53364334  0.25576245 -0.82615639]]


In [25]:
o = SVC(kernel='linear')
lm = o.fit(X_train, y_train)
print(lm)

SVC(kernel='linear')


In [26]:
b = lm.predict(X_test)
print(b)

[0 0 0 1 1 0 0 0 1 1 0 0 0 1 0 1 1 1 1 1 0 1 1 0 1 0 1 0 0 1 0 0 1 0 0 0 1
 1 0 1 0 1 0 0 0 0 0 1 1 1 0 1 0 0 0 0 0 1 1 1 1 0 1 1 0 0 0 1 1 0 1 1 0 0
 0 1 1 1 0 1 0 0 1 1 0 0 1 0 1 0 1 1 0 1 0 0 1 1 1 1 1 0 1 1 1 1 0 0 1 0 0
 1 1 1 1 0 1 1 0 0 1 1 0 1 0 1 0 0 0 1 1 1 0 0 0 0 1 1 0 0 1 0 0 0 0 0 0 0
 1 0 0 1 0 0 0 0 1 1 1 0 0 0 0 0 1 0 0 0 0 1 0 0 1 1 1 1 1 1 0 0 0 0 1 0 1
 1 0 1 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 0 1 1 1 0 0 1 1 0 0 1 0 0
 1 0 0 0 1 0 0 0 1 1 1 0 1 1 0 0 0 1 0 1 0 0 0 1 1 0 0 1 1 0 1 1 1 1 0 0 0
 0 1 1 1 0 0 1 0 0 0 0 0 1 0 1 0]


In [27]:
f = classification_report(y_test,b)
print(f)

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       150
           1       0.99      0.99      0.99       125

    accuracy                           0.99       275
   macro avg       0.99      0.99      0.99       275
weighted avg       0.99      0.99      0.99       275



In [28]:
m = confusion_matrix(y_test,b)
print(m)

[[149   1]
 [  1 124]]


In [30]:
n = accuracy_score(y_test,b)
print(n)

0.9927272727272727
